services:
  backend:
    build: ./backend
    env_file: ".env"
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: ./app
        - action: rebuild
          path: ./backend/go.mod
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    env_file: ".env"
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    env_file: ".env"
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: ./app
        - action: rebuild
          path: ./frontend/package.json

volumes:
  db-data:
